{
 "title": "Pizza Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Create Pizza Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "pizza_req_latency_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Server Latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "total_latency_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "Server Latency "
    }
   ]
  },
  {
   "title": "Authentication",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "auth_attempts_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "success"
    },
    {
     "expr": "failed_auth_attempts_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "fail"
    }
   ]
  },
  {
   "title": "Revenue",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "revenue_per_minute_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 5, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "memory_used_percent{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU usage",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 5, "x": 10, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "cpu_used_percent{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Number of Active Users",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 15, "y": 8 },
   "targets": [
    {
     "expr": "number_active_users_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "Active Users"
    }
   ]
  },
  {
   "title": "Pizza Purchases",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "pizza_sold_per_minute_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "Pizza Purchases"
    }
   ]
  },
  {
   "title": "Number of Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "Req_per_minute_total_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "Total"
    },
    {
     "expr": "Req_per_minute_delete_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "Delete"
    },
    {
     "expr": "Req_per_minute_get_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "Get"
    },
    {
     "expr": "Req_per_minute_post_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "POST"
    },
    {
     "expr": "Req_per_minute_put_ratio{source=\"jwt-pizza-service-development-testing\"}",
     "legendFormat": "PUT"
    }
   ]
  }
 ]
}